### ISSUE TITLE
Question About Helicorder

### ISSUE THREAD

**Issue by abhishek73magar** [crotwell/seisplotjs#37]
is possible to show two timezone in helicorder graph like left side Y-axis UTC time and right side Y-axis local time? need little help
if any example do you have please share us.

thank you in advance.

**Comment by Coder73-avi** [comment]
Thank you for quick response 

I have a little suggestion for local time because UTC time in left side and local time in right side but YLabelRightTimeZone is set as string like local or other time zone time must be startTime not end time if its YLabelRighttimeZone is set must be used endTime

```
 if(typeof this.heliConfig.yLabelTimeZone === 'string' && typeof this.heliConfig.yLabelRightTimeZone === 'object'){
        lineSeisConfig.yLabelRight = `${endTime?.setZone(this.heliConfig.yLabelTimeZone).toFormat("HH:mm")}`;
      } else {
        if(typeof this.heliConfig.yLabelRightTimeZone === 'string') {
          lineSeisConfig.yLabelRight = `${startTime?.setZone(this.heliConfig.yLabelRightTimeZone).toFormat("HH:mm")}`;
        } else lineSeisConfig.yLabelRight = `${endTime?.setZone(this.heliConfig.yLabelRightTimeZone).toFormat("HH:mm")}`;
      }
```  

I just modify this plz check and consider once  and your standalone.mjs is alpha.1 in your gallery docs plz correct it

thank you very much

**Comment by Coder73-avi** [comment]
How we can use ...standalone.mjs in react application any idea plz share me.

**Comment by crotwell** [comment]
I don't understand why you would want the time on the right side to be the start time of the line. That seems very confusing to me.

I don't use react, but you may be better off using the npm package instead of the standalone.

**Comment by abhishek73magar** [comment]
thanks,
I understood. thank you for quick response
